apiVersion: v1
kind: Service
metadata:
  name: java-rest-api-clusterip
  labels:
    app: java-rest-api
spec:
  type: ClusterIP
  selector:
    app: java-rest-api
  ports:
    - name: http
      port: 5050
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: java-rest-api-nodeport
  labels:
    app: java-rest-api
spec:
  type: NodePort
  selector:
    app: java-rest-api
  ports:
    - name: http
      port: 5050
      targetPort: http
      nodePort: 30050
