apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: shiladitya997/fastapi_basic_app
    newTag: b854170e518bc9fbac22a10f10ef4066f8352182
